document.addEventListener('DOMContentLoaded', () => {
    const nav = document.querySelector('nav');
    const selector = document.createElement('div');
    selector.className = 'selector-idioma';
    selector.innerHTML = '<select id="idioma" aria-label="Seleccionar idioma"><option value="es">ES</option><option value="en">EN</option></select>';
    nav.appendChild(selector);

    const textos = [
        ['nav ul li:nth-child(1) a','Historia','Our Story'],['nav ul li:nth-child(2) a','La Finca','The Farm'],['nav ul li:nth-child(3) a','Nuestro Café','Our Coffee'],['nav ul li:nth-child(4) a','Galería','Gallery'],['nav ul li:nth-child(5) a','Contacto','Contact'],
        ['.ubicacion','DESDE LAS MONTAÑAS DE JINOTEGA · NICARAGUA','FROM THE MOUNTAINS OF JINOTEGA · NICARAGUA'],['.hero p','Cultivado con pasión.<br>Compartido con orgullo.','Grown with passion.<br>Shared with pride.'],['.boton','Conoce Nuestra Historia','Discover Our Story'],
        ['.historia .subtitulo','NUESTRA HISTORIA','OUR STORY'],['.historia h2','Un sueño de Sergio Rodríguez','A dream of Sergio Rodríguez'],
        ['.historia p:nth-of-type(1)','Loma Azul Coffee nació de un sueño: <strong>tener una finca propia y producir café de alta calidad</strong>.','Loma Azul Coffee was born from a dream: <strong>to have our own farm and produce high-quality coffee</strong>.'],
        ['.historia p:nth-of-type(2)','Ese sueño llevó a Sergio a asumir el reto de adquirir un terreno y comenzar, poco a poco, a construir una finca de café. Lo que comenzó como una iniciativa personal se ha convertido en un <strong>proyecto familiar</strong>, con la ilusión de seguir creciendo juntos.','That dream led Sergio to take on the challenge of acquiring a piece of land and, little by little, building a coffee farm. What began as a personal initiative has become a <strong>family project</strong>, with the hope of growing together.'],
        ['.historia p:nth-of-type(3)','<strong>Nuestro enfoque está en la calidad</strong>, en cuidar cada detalle y en aprovechar las condiciones privilegiadas de <strong>San Rafael del Norte, Jinotega</strong>, para producir un café del que podamos sentirnos orgullosos.','<strong>Our focus is on quality</strong>, caring for every detail and taking advantage of the privileged conditions of <strong>San Rafael del Norte, Jinotega</strong>, to produce coffee we can be proud of.'],
        ['.historia p:nth-of-type(4)','Cuando llegamos, estos terrenos eran potreros. Desde entonces, poco a poco, hemos venido estableciendo café, árboles maderables y frutales, transformando el paisaje y construyendo un ecosistema más diverso.','When we arrived, these lands were pasture. Since then, little by little, we have been establishing coffee, timber trees and fruit trees, transforming the landscape and building a more diverse ecosystem.'],
        ['.historia p:nth-of-type(5)','<strong>Este es apenas el comienzo.</strong> Queremos que Loma Azul siga creciendo con nuestra familia, una cosecha a la vez.','<strong>This is only the beginning.</strong> We want Loma Azul to keep growing with our family, one harvest at a time.'],
        ['.historia-cierre','Un sueño de Sergio Rodríguez. <span>Un proyecto de familia.</span>','A dream of Sergio Rodríguez. <span>A family project.</span>'],
        ['#finca .titulo-seccion span','LA FINCA','THE FARM'],['#finca .titulo-seccion h2','El origen de cada taza','The origin of every cup'],['#finca .titulo-seccion p','Ubicada en Santa Martha de Loma Azul, San Rafael del Norte, Jinotega.','Located in Santa Martha de Loma Azul, San Rafael del Norte, Jinotega.'],
        ['.finca-overline','LOMA AZUL COFFEE','LOMA AZUL COFFEE'],['.finca-info h3','Donde comienza nuestro café','Where our coffee begins'],
        ['.finca-lead','Un entorno de montaña donde la altura, el clima y el trabajo de nuestra familia se encuentran para cultivar café con identidad y calidad.','A mountain environment where elevation, climate and our family’s work come together to grow coffee with identity and quality.'],
        ['.finca-lugar','<strong>Santa Martha de Loma Azul</strong><br>San Rafael del Norte · Jinotega · Nicaragua','<strong>Santa Martha de Loma Azul</strong><br>San Rafael del Norte · Jinotega · Nicaragua'],
        ['.finca-dato:nth-child(1) span','Altitud','Elevation'],['.finca-dato:nth-child(1) small','metros sobre el nivel del mar','meters above sea level'],
        ['.finca-dato:nth-child(2) span','Variedades','Varieties'],['.finca-dato:nth-child(2) small','Parainema','Parainema'],
        ['.finca-dato:nth-child(3) span','Proceso','Process'],['.finca-dato:nth-child(3) small','Procesamiento enfocado en preservar la calidad','Processing focused on preserving quality'],
        ['.finca-dato:nth-child(4) span','Origen','Origin'],['.finca-dato:nth-child(4) small','Montañas de San Rafael del Norte','Mountains of San Rafael del Norte'],
        ['.finca-frase','“El origen de cada taza comienza aquí.”','“The origin of every cup begins here.”'],
        ['#cafe .titulo-seccion span','NUESTRO CAFÉ','OUR COFFEE'],['#cafe .titulo-seccion h2','De la montaña a tu taza','From the mountain to your cup'],['#cafe .titulo-seccion p','Cada etapa del proceso se realiza con dedicación para ofrecer un café que refleje el origen y la calidad de Loma Azul Coffee.','Every stage of the process is carried out with care to offer a coffee that reflects the origin and quality of Loma Azul Coffee.'],
        ['#cafe .timeline-item:nth-child(1) h3','🌸 Floración','🌸 Blossom'],['#cafe .timeline-item:nth-child(1) p','Todo comienza con la flor del café.','It all begins with the coffee blossom.'],['#cafe .timeline-item:nth-child(2) h3','🍒 Cosecha','🍒 Harvest'],['#cafe .timeline-item:nth-child(2) p','Seleccionamos únicamente las cerezas maduras.','We select only ripe coffee cherries.'],['#cafe .timeline-item:nth-child(3) h3','💧 Beneficiado','💧 Processing'],['#cafe .timeline-item:nth-child(3) p','Procesamos el café con método lavado.','We process the coffee using the washed method.'],['#cafe .timeline-item:nth-child(4) h3','☀️ Secado','☀️ Drying'],['#cafe .timeline-item:nth-child(4) p','El secado lento conserva la calidad del grano.','Slow drying preserves the quality of the bean.'],['#cafe .timeline-item:nth-child(5) h3','🔥 Tueste','🔥 Roasting'],['#cafe .timeline-item:nth-child(5) p','Buscamos resaltar las mejores características del café.','We seek to highlight the coffee’s finest characteristics.'],['#cafe .timeline-item:nth-child(6) h3','☕ Tu taza','☕ Your cup'],['#cafe .timeline-item:nth-child(6) p','Finalmente disfrutas una taza con origen y trazabilidad.','Finally, you enjoy a cup with origin and traceability.'],
        ['#galeria .titulo-seccion span','GALERÍA','GALLERY'],['#galeria .titulo-seccion h2','Conoce nuestra finca','Discover our farm'],['#galeria .titulo-seccion p','Imágenes reales de Loma Azul Coffee y del entorno donde cultivamos nuestro café.','Real images of Loma Azul Coffee and the surroundings where we grow our coffee.'],
        ['#contacto .titulo-seccion span','CONTACTO','CONTACT'],['#contacto .titulo-seccion h2','Hablemos de café','Let’s Talk Coffee'],['#contacto .titulo-seccion p','Gracias por conocer nuestra historia. Cada taza representa el esfuerzo, la dedicación y el amor por el café cultivado en nuestras montañas.','Thank you for learning about our story. Every cup represents the effort, dedication, and love behind the coffee grown in our mountains.'],['#contacto .contacto-card:nth-child(1) h3','📍 Ubicación','📍 Location'],['#contacto .contacto-card:nth-child(2) h3','🌱 Variedades','🌱 Varieties'],['#contacto .contacto-card:nth-child(3) h3','💧 Proceso','💧 Process'],
        ['footer .footer-contenido p:nth-of-type(1)','Cultivado con pasión. Compartido con orgullo.','Grown with passion. Shared with pride.'],['.whatsapp-texto','Escríbenos por WhatsApp','Message us on WhatsApp']
    ];

    const elementos = textos.map(([s,es,en]) => { const el=document.querySelector(s); if(el){el.dataset.es=es;el.dataset.en=en;} return el; }).filter(Boolean);
    const cambiarIdioma = idioma => { elementos.forEach(el => el.innerHTML=el.dataset[idioma]); document.documentElement.lang=idioma; localStorage.setItem('lomaAzulIdioma',idioma); selector.querySelector('select').value=idioma; };
    selector.querySelector('select').addEventListener('change', e => cambiarIdioma(e.target.value));
    const guardado=localStorage.getItem('lomaAzulIdioma');
    cambiarIdioma(guardado || (navigator.language && navigator.language.toLowerCase().startsWith('en') ? 'en' : 'es'));

    const style=document.createElement('style');
    style.textContent=`
        .selector-idioma{display:flex;align-items:center;gap:6px;margin-left:18px;flex-shrink:0}.selector-idioma select{appearance:none;-webkit-appearance:none;border:1px solid rgba(255,255,255,.35);background:rgba(255,255,255,.08);color:#fff;border-radius:20px;padding:6px 10px;font:600 11px 'Poppins',sans-serif;letter-spacing:.6px;cursor:pointer;outline:none}.selector-idioma select option{background:#211b16;color:#fff}.selector-idioma select:focus{border-color:#d6a45a}
        .scroll-indicator-simple{position:absolute;left:12%;bottom:24px;color:#fff;font-size:22px;opacity:.78;animation:flotar 1.8s infinite}
        @media(max-width:900px){.selector-idioma{margin-left:0;margin-top:4px}.selector-idioma select{padding:6px 9px}.scroll-indicator-simple{left:8%}}
        @media(max-width:600px){.scroll-indicator-simple{left:7%}}
    `;
    document.head.appendChild(style);
});